### ISSUE TITLE
NameError: name 'self' is not defined

### ISSUE THREAD

**Issue by danmechanic** [danmechanic/glucid#4]
[mechanic@luddite glucid]$ glucid --set_gain="+4"
----------------------------------------

glucid and glucid8824.py:
Copyright (C) 2017,2018 Daniel R Mechanic
GPL version 3 ONLY <http://gnu.org/licenses/gpl.html>.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to
change and redistribute it under certain circumstances;
For details see LICENSE
----------------------------------------
Using /dev/ttyUSB0 to connect to lucid ID 00

Traceback (most recent call last):
  File "/home/mechanic/anaconda3/bin/glucid", line 11, in <module>
    sys.exit(main())
  File "/home/mechanic/anaconda3/lib/python3.6/site-packages/glucid/glucid8824.py", line 1456, in main
    if self.siface in self.DEVICES['rs232']:
NameError: name 'self' is not defined

**Comment by danmechanic** [comment]
Need to remove all the code that was intended to make this work for both rs232 and midi, since that was a misunderstanding of the midi platform

**Comment by danmechanic** [comment]
removed this code....   removing all code associated with the midi version of the 8824 *this code was t determine if the unit was midi or rs232 

fixed.
